// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyToChucAPI.Data;

#nullable disable

namespace QuanLyToChucAPI.Migrations.QuanLyToChuc
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240628085247_InitialCreateForQuanLyToChuc")]
    partial class InitialCreateForQuanLyToChuc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyToChucAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViCongTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLyToChucAPI.Models.NguoiLienHe", b =>
                {
                    b.Property<int>("NguoiLienHeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiLienHeID"));

                    b.Property<string>("ChucDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiLienHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDemVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToChucID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("NguoiLienHeID");

                    b.HasIndex("ToChucID");

                    b.ToTable("NguoiLienHes");
                });

            modelBuilder.Entity("QuanLyToChucAPI.Models.PhuongThucLienLac", b =>
                {
                    b.Property<int>("PhuongThucLienLacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhuongThucLienLacID"));

                    b.Property<int>("LoaiLienLac")
                        .HasColumnType("int");

                    b.Property<int>("LoaiNguoiLienLac")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToChucID")
                        .HasColumnType("int");

                    b.HasKey("PhuongThucLienLacID");

                    b.HasIndex("ToChucID");

                    b.ToTable("PhuongThucLienLacs");
                });

            modelBuilder.Entity("QuanLyToChucAPI.Models.ThongTinDinhDanh", b =>
                {
                    b.Property<int>("ThongTinDinhDanhID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThongTinDinhDanhID"));

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToChucID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("ThongTinDinhDanhID");

                    b.HasIndex("ToChucID");

                    b.ToTable("ThongTinDinhDanhs");
                });

            modelBuilder.Entity("QuanLyToChucAPI.Models.ToChuc", b =>
                {
                    b.Property<int>("ToChucID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToChucID"));

                    b.Property<string>("AnhUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinhVucChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrucThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToChucID");

                    b.ToTable("ToChucs");
                });

            modelBuilder.Entity("QuanLyToChucAPI.Models.NguoiLienHe", b =>
                {
                    b.HasOne("QuanLyToChucAPI.Models.ToChuc", "ToChuc")
                        .WithMany("NguoiLienHes")
                        .HasForeignKey("ToChucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToChuc");
                });

            modelBuilder.Entity("QuanLyToChucAPI.Models.PhuongThucLienLac", b =>
                {
                    b.HasOne("QuanLyToChucAPI.Models.ToChuc", "ToChuc")
                        .WithMany("PhuongThucLienLacs")
                        .HasForeignKey("ToChucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToChuc");
                });

            modelBuilder.Entity("QuanLyToChucAPI.Models.ThongTinDinhDanh", b =>
                {
                    b.HasOne("QuanLyToChucAPI.Models.ToChuc", "ToChuc")
                        .WithMany("ThongTinDinhDanhs")
                        .HasForeignKey("ToChucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToChuc");
                });

            modelBuilder.Entity("QuanLyToChucAPI.Models.ToChuc", b =>
                {
                    b.Navigation("NguoiLienHes");

                    b.Navigation("PhuongThucLienLacs");

                    b.Navigation("ThongTinDinhDanhs");
                });
#pragma warning restore 612, 618
        }
    }
}
